### ISSUE TITLE
Memory limits per player

### ISSUE THREAD

**Issue by S-S-X** [BuckarooBanzay/digiline_global_memory#1]
There should be memory limits / player.
I was able to push a lot of garbage to memory, it will stay there until server restart and if data will be stored / restored over restarts then this can be even bigger problem as single player can easily consume significant amounts of lua memory on server.

I did not really optimize ram writer at all and was still able to push significant amount of garbage to memory. (btw, accidentally crashed mapserver while doing this...)

I did use just 10 writers (lua controllers) each sending garbage data 5 - 40kb / message around 1 second intervals.
If I did quick math correctly that should be maybe around 0,2mb / second average and 12mb / minute.

**Comment by S-S-X** [comment]
This is meant to store simple data like numbers or short text, if say 1 - 5mb is allowed per user how many numbers can be stored to table? enough, no problems.
How much text? Multiple large books.
Cat pics? Maybe 10 - 1000 avg web cat pics depending on quality.

**Comment by BuckarooBanzay** [comment]
>  Cat pics? Maybe 10 - 1000 avg web cat pics depending on quality.

:smile: 

I'm not yet sure if this is gonna be an expert tool without limit or a dummy tool with lots of protections/checks. Maybe there are already checks from the `digiline_send` function that ensure some size constraints, but i haven't got that far yet :stuck_out_tongue:

**Comment by S-S-X** [comment]
Take a look at lua vm ram graph for 2.5. - 3.5. night.. I did try pushing some garbage there, max was around 40k / digiline message before it complained about message size.

![image](https://user-images.githubusercontent.com/50966843/80953942-21b96400-8e05-11ea-9f3c-88cfe48e9d08.png)

**Comment by BuckarooBanzay** [comment]
fixed with 38b1435367012d53dc73bf47e7546cc6b5ce83dd
